export const dayData = [{
    dayNumber: 'Day One',
    morning: [{
        id: 0,
        name: 'Student Meet and Greet',
        time: '11:00AM',
        numberOfPhotos: 1,
        description: ['The cohort is given a chance to get to know each other. In 2025, this event was held at the Museum of Broadway, followed by a tour.'],
        imgURL: ['src/walkthrough/walkthroughElements/photos/groupPhoto.jpg'],
    }],
    lunch: '12:30PM',
    afternoon: [{
        id: 0,
        name: 'Performance',
        time: '2:00PM',
        numberOfPhotos: 1,
        description: ['The cohort typically sees a matinee production.', 'In 2025, the cohort saw John Proctor is the Villain.'],
        imgURL: ['src/walkthrough/walkthroughElements/photos/johnProctor.jpg'],
    },],
    EOD: '4:00PM',
}, {
    dayNumber: 'Day Two',
    morning: [{
        id: 0,
        name: 'SB2D Orientation ',
        time: '8:30AM',
        numberOfPhotos: 0,
        description: ['An introduction to key instructors and an overview of community guidelines'],
        imgURL: ['src/walkthrough/walkthroughElements/photos/day2LightingA.jpg'],
    }, {
        id: 1,
        name: 'Intro to Design Disciplines',
        time: '10:00AM',
        numberOfPhotos: 0,
        description: ['An activity based overview of theatre design disciplines led by designers in the field.'],
        imgURL: ['src/walkthrough/walkthroughElements/photos/day2LightingB.jpg'],
    }, {
        id: 2,
        name: 'Discipline Workshop',
        time: '11:00AM',
        numberOfPhotos: 3,
        description: ['Discipline workshops are interactive explorations of a single design discipline led by a designer in the field.', 'In 2025, Clifton Taylor led a workshop on lighting design, joined by associate Deandra Bromfield.', 'Clifton Taylor’s work has been commissioned on Broadway, Off-Broadway, regionally, and in seventeen countries outside the US. He has taught and lectured at UNCSA, NYU, Yale, the New York Choreographic Institute, LDI, Showlight, Juilliard School, the University of Iowa, and the Royal University of Fine Arts in Phnom Penh, Cambodia.'],
        imgURL: ['src/walkthrough/walkthroughElements/photos/day2LightingC.jpg'],
    }],
    lunch: '1:00PM',
    afternoon: [{
        id: 0,
        name: 'Model Box Creation Workshop',
        time: '2:00PM',
        numberOfPhotos: 5,
        description: ['Donyale Werle leads a hands-on activity where students build their own model box using a variety of materials. Donyale Werle is a Tony & Obie winning Broadway set designer, now garden designer, horticulturist and flower farmer. She is known for her work in artistic sustainability.'],
        imgURL: [],
    }, {
        id: 1,
        name: 'Advocating for Yourself Discussion',
        time: '5:00PM',
        numberOfPhotos: 0,
        description: ['In 2025, guests Sophia Skiles, Frankie Charles, and Cody Renard Richard joined the cohort for a discussion about advocating for yourself and living your artistic truth.'],
        imgURL: [],
    }],
    EOD: '7:00PM',
}, {
    dayNumber: 'Day Three',
    morning: [{
        id: 0,
        name: 'Tour',
        time: '',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Discipline Workshop',
        time: '11:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    lunch: '2:00PM',
    afternoon: [{
        id: 0,
        name: 'Discipline Workshop',
        time: '3:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Dinner',
        time: '5:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 2,
        name: 'Performance',
        time: '7:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    EOD: '10:00PM'
}, {
    dayNumber: 'Day Four',
    morning: [{
        id: 0,
        name: 'Costume Shop Visit',
        time: '9:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    lunch: '11:30AM',
    afternoon: [{
        id: 0,
        name: 'Performance',
        time: '2:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Dinner',
        time: '6:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 2,
        name: 'Lincoln Center Summer for the City',
        time: '7:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    EOD: '10:30PM'
}, {
    dayNumber: 'Day Five',
    morning: [{
        id: 0,
        name: 'Discipline Workshop',
        time: '9:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Discipline Workshop',
        time: '11:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    lunch: '12:00PM',
    afternoon: [{
        id: 0,
        name: 'Discipline Workshop',
        time: '3:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Dinner',
        time: '5:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 2,
        name: 'Performance',
        time: '7:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    EOD: '10:30PM'
}, {
    dayNumber: 'Day Six',
    morning: [{
        id: 0,
        name: 'Discipline Workshop',
        time: '',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Final Project',
        time: '',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    lunch: '12:30PM',
    afternoon: [{
        id: 0,
        name: 'Final Project',
        time: '1:30PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Dinner',
        time: '5:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 2,
        name: 'Performance',
        time: '7:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    EOD: '10:30PM'
}, {
    dayNumber: 'Day Seven',
    morning: [{
        id: 0,
        name: 'Final Project',
        time: '9:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Path After High School Conversation ',
        time: '10:00AM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    lunch: '12:00PM',
    afternoon: [{
        id: 0,
        name: 'Final Project Presentation',
        time: '1:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 1,
        name: 'Final Group Discussion',
        time: '4:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 2,
        name: 'Dinner',
        time: '5:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }, {
        id: 3,
        name: 'Performance',
        time: '7:00PM',
        numberOfPhotos: 0,
        description: '',
        imgURL: [],
    }],
    EOD: '10:30PM'
}]

